//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPowerMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPowerDBEntities : DbContext
    {
        public MyPowerDBEntities()
            : base("name=MyPowerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Permissions> T_Permissions { get; set; }
        public virtual DbSet<T_RoleInfo> T_RoleInfo { get; set; }
        public virtual DbSet<T_RoleToPermissions> T_RoleToPermissions { get; set; }
        public virtual DbSet<T_UserInfo> T_UserInfo { get; set; }
        public virtual DbSet<T_UserToRole> T_UserToRole { get; set; }
    }
}
