//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPowerMS.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 角色权限关联表  
    /// </summary>
    public partial class T_RoleToPermissions
    {
        /// <summary>  
    	/// 主键  
    	/// </summary> 
        public string id { get; set; }
        /// <summary>  
    	/// 角色id  
    	/// </summary> 
        public string RoleId { get; set; }
        /// <summary>  
    	/// 权限id  
    	/// </summary> 
        public string Permissions { get; set; }
    }
}
