//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPowerMS.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 角色  
    /// </summary>
    public partial class T_RoleInfo
    {
        /// <summary>  
    	/// 主键  
    	/// </summary> 
        public string id { get; set; }
        /// <summary>  
    	/// 角色名称  
    	/// </summary> 
        public string RoleName { get; set; }
        /// <summary>  
    	/// 角色描述  
    	/// </summary> 
        public string RoleDesc { get; set; }
        /// <summary>  
    	/// 创建日期  
    	/// </summary> 
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
