//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPowerMS.Models
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 用户信息表  
    /// </summary>
    public partial class T_UserInfo
    {
        /// <summary>  
    	/// 主键  
    	/// </summary> 
        public string id { get; set; }
        /// <summary>  
    	/// 用户名  
    	/// </summary> 
        public string UserName { get; set; }
        /// <summary>  
    	/// 真实姓名  
    	/// </summary> 
        public string TrueName { get; set; }
        /// <summary>  
    	/// 密码  
    	/// </summary> 
        public string PassWord { get; set; }
        /// <summary>  
    	/// 角色  
    	/// </summary> 
        public string Role { get; set; }
        /// <summary>  
    	/// 创建日期  
    	/// </summary> 
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
